@startuml


    package de.gematik.ti.cardreader.provider.usb.tactivo.control {
      class TactivoCallback {
          - context : Context
          - terminalId : int
          ~ terminalType : int
          {static} - LOG : Logger
          + TactivoCallback()
          + connect()
          + initializationFailed()
          + initialized()
          + uninitialized()
          + onReceive()
          - onDeviceDetached()
          - onDeviceAttached()
      }
    }

  TactivoCallback -up-|> PBInitializedCallback
  TactivoCallback -up-|> BroadcastReceiver

@enduml
